### ISSUE TITLE
[Umbrella] Release InLong 1.12.0

### ISSUE THREAD

**Issue by baomingyu** [apache/inlong#10031]
### Describe the proposal

To release 1.12.0, refer to #9655

### Task list

- [x] #10024 
- [x] #10025 
- [x] #10026 
- [x] #10027 
- [x] #10028 
- [x] #10029 
- [x] #10030 
- [x] https://github.com/apache/inlong-website/issues/938
- [x] https://github.com/apache/inlong-website/issues/939
- [x] https://github.com/apache/inlong-website/issues/940

### InLong Component

Other for not specified component

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
