### ISSUE TITLE
Tencent Rhino-bird Open-source Training Program 2024

### ISSUE THREAD

**Issue by vernedeng** [apache/inlong#10497]
### Describe the proposal

In 2021, Tencent released the "Rhino Bird Open Source Talent Training Program" for the first time. By creating open-source courses and practical training programs for college students, the program aims to cultivate open-source talent, popularize open-source culture, and promote the development of the open-source talent ecosystem. The program is jointly guided by the Ministry of Education's Computer Science Teaching Guidance Committee, Software Engineering Teaching Guidance Committee, Electronic Information Teaching Guidance Committee, and China Academy of Information and Communications Technology. It is co-sponsored by Tencent Open Source and Tencent University Cooperation, and the training plan covers three stages: open-source basic courses, advanced research and study, and open-source project practice.

In 2024, the program will continue to focus on industry technology hotspots, providing real-world enterprise projects and development scenarios, offering star projects and open-source mentors in five core technology areas: front-end, AI, big data, basic platforms, and databases.

Students can register to participate in online open-source series courses, learn about open-source knowledge, and engage in conversations with experts from academia and industry. Students selected for open-source project practice will receive one-on-one guidance from mentors, engage in programming practice, and have the opportunity to obtain a Tencent Open Source Contributor Certificate (only 30+ have been issued worldwide so far). For more project information, please visit: https://opensource.tencent.com//summer-of-code

https://github.com/Tencent/OpenSourceTalent/issues/39

### Task list

- Easy
    - [x] #10463 
    - [x] #10464 
    - [ ] https://github.com/apache/inlong-website/issues/956
    - [x] #7056
- Middle
    - [ ] #10465 
    - [x] #10287 
    - [x] #10288 
    - [x] #10289 
    - [x] #10286 
- Hard
    - [ ] #10466
    - [x] #10467 
    - [x] #6536 

- Tencent Open Source Project Practical Training
    - [x] #10798 
    - [x] #10797 
    - [x] #10796 

### InLong Component

Other for not specified component

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by vernedeng** [comment]
Thanks to all the contributors, the Tencent Rhino-bird 2024 is finished, and this issue will be closed.
