### ISSUE TITLE
[Roadmap] Apache InLong Roadmap 2022 H1

### ISSUE THREAD

**Issue by dockerzhang** [apache/inlong#2318]
### Description

Hello, everyone, we made a roadmap for 2022 recently, welcome to discuss and contribute.

### Overview
![InLong](https://user-images.githubusercontent.com/18047329/150743242-27bdf353-074b-4600-8b6a-885e3dbede5f.png)

### Goal
1, Create a pluggable architecture for all modules, especially for `agent`(source) and `sort`(sink).
2, Add offline data streams management for InLong.
3, Cover common data sources, data types, and data destinations.

### Tasks
1. System
- [x] #1883
- [x] #1307
- [x] #1780
- [x] #1308
- [x] #2301

2. Manager
- [x] #2302
- [x] #2303
- [x] #2304
- [x] #2305
- [ ] #2306
- [ ] #2308

3. Agent
- [x] #2309
- [ ] #2310
- [x] #2311
- [x] #2312

4. DataProxy
- [x] #2313
- [x] #2249
- [ ] #1309

5. Sort
- [x] #1715
- [x] #1714
- [x] #2250
- [x] #2314
- [x] #2315
- [x] #2183

6. Community
- [x] plan two developer meetup
- [x] #2281
- [x] #1810

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by shink** [comment]
I did some work to support Kubernetes for InLong in #1308, and fixed some reference and configuration bugs in #1562, but there is still some work to do, such as adding some configuration items, completing related documents, etc. I will complete these tasks in 2022.

**Comment by dockerzhang** [comment]
for #https://github.com/apache/inlong/issues/4990 created, this issue will close. all unfinished tasks will be added to the new roadmap issue.
