### ISSUE TITLE
[Feature][Sort] Sort-standalone support data flow to CLS

### ISSUE THREAD

**Issue by vernedeng** [apache/inlong#2576]
### Description

- [x] #2649  Define cls profile event
- [x] #2650  Define sort stand-alone CLS translator
- [x] #2651  Add CLS sink
- [x] #2730 Stand-alone CLS sink reduce the number of AsyncProducerClient

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
