### ISSUE TITLE
[Umbrella][SDK] Support C++ SDK for DataProxy

### ISSUE THREAD

**Issue by dockerzhang** [apache/inlong#4960]
### Subtasks

- [x] #5249
- [x] #5251
- [x] #5253
- [x] #5256
- [x] #5258
- [x] #5265
- [x] #5267
- [x] #5270

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by pocozh** [comment]
get

**Comment by pocozh** [comment]
- [ ] https://github.com/apache/inlong/issues/5249
- [ ] https://github.com/apache/inlong/issues/5251
- [ ] https://github.com/apache/inlong/issues/5253
- [ ] https://github.com/apache/inlong/issues/5256
- [ ] https://github.com/apache/inlong/issues/5258
- [ ] https://github.com/apache/inlong/issues/5265
- [ ] https://github.com/apache/inlong/issues/5267
- [ ] https://github.com/apache/inlong/issues/5270
