### ISSUE TITLE
[Feature][DataProxy] Golang SDK

### ISSUE THREAD

**Issue by dockerzhang** [apache/inlong#4961]
### Description

Java SDK Code：
https://github.com/apache/inlong/tree/master/inlong-sdk/dataproxy-sdk

Java SDK Example：
https://inlong.apache.org/docs/next/sdk/dataproxy-sdk/example

C++ SDK：
https://github.com/apache/inlong/issues/4960

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by JHQY** [comment]
Zhang Jiang,  Hong Shiyu will complete this task:)

**Comment by asidunfeiguo** [comment]
###Motivation
To build DataProxy Golang SDK, support sending message and load balance.
###Design
We divided the task into 7 subtasks :

- [ ] Add utils file for DataProxy Golang SDK
- [ ] Add proxy config and manager for DataProxy Golang SDK
- [ ] Add buffer manager for DataProxy Golang SDK
- [ ] Support network operation and managment for DataProxy Golang SDK
- [ ] Add core interface for DataProxy Golang SDK
- [ ] Add config file and demo for DataProxy Golang SDK
- [ ] Add unit tests for DataProxy Golang SDK

**Comment by asidunfeiguo** [comment]
### Motivation
To build DataProxy Golang SDK, support sending message and load balance.
### Design
We divided the task into 7 subtasks :

- [ ] Add utils file for DataProxy Golang SDK
- [ ] Add proxy config and manager for DataProxy Golang SDK
- [ ] Add buffer manager for DataProxy Golang SDK
- [ ] Support network operation and managment for DataProxy Golang SDK
- [ ] Add core interface for DataProxy Golang SDK
- [ ] Add config file and demo for DataProxy Golang SDK
- [ ] Add unit tests for DataProxy Golang SDK

**Comment by rhizoma-atractylodis** [comment]
I want to do this task

**Comment by JasonChen86899** [comment]
@dockerzhang hi, i am also work in tencent, know and learn inlong a lot recently. can i do this task or do some submit of this

**Comment by rhizoma-atractylodis** [comment]
## Planning the following
- [ ] Add proxy config and manager for DataProxy Golang SDK (Imitate the implementation of Java-sdk)
- [ ] Add buffer manager for DataProxy Golang SDK
- [ ] Support network operation and managment for DataProxy Golang SDK（use go-netty）
- [ ] Add core interface for DataProxy Golang SDK (Sender interface with sendMessage method)
- [ ] Add config file and demo for DataProxy Golang SDK (make fields configurable)
- [ ] Add unit tests for DataProxy Golang SDK

**Comment by xuehuanran** [comment]
I will complete this feature
