### ISSUE TITLE
Apache InLong Roadmap 2022 H2

### ISSUE THREAD

**Issue by dockerzhang** [apache/inlong#4990]
### Description

the roadmap for the latter half of 2022.

## Goal
- Cover more usage scenarios
- Improve the supporting capabilities of the system
- lower the threshold for the use of the system

## Overview
![2022 H2 InLong](https://user-images.githubusercontent.com/18047329/178232234-95150d07-33bb-472b-a333-eb07b16d5dd7.png)

### System
- [x] https://github.com/apache/inlong/issues/4957
- [x] https://github.com/apache/inlong/issues/4958
- [ ] https://github.com/apache/inlong/issues/1737
- [x] https://github.com/apache/inlong/issues/4959
- [ ] https://github.com/apache/inlong/issues/4963

### DataProxy
- [x] https://github.com/apache/inlong/issues/1309
- [x] https://github.com/apache/inlong/issues/4960
- [ ] https://github.com/apache/inlong/issues/4961
- [x] https://github.com/apache/inlong/issues/4962
- [x] https://github.com/apache/inlong/issues/5101

### Sort
- [x] https://github.com/apache/inlong/issues/4964
- [ ] https://github.com/apache/inlong/issues/4966
- [x] https://github.com/apache/inlong/issues/4967
- [x] Add more connectors, like Apache Doris

### TubeMQ
- [x] https://github.com/apache/inlong/issues/1177
- [ ] https://github.com/apache/inlong/issues/4968
- [x] https://github.com/apache/inlong/issues/4969
- [ ] https://github.com/apache/inlong/issues/1524
- [ ] https://github.com/apache/inlong/issues/4972

### Manager
- [x] https://github.com/apache/inlong/issues/4932
- [ ] https://github.com/apache/inlong/issues/2306
- [ ] https://github.com/apache/inlong/issues/4973
- [x] https://github.com/apache/inlong/issues/4974
- [ ] https://github.com/apache/inlong/issues/4975
- [x] https://github.com/apache/inlong/issues/4976

### Dashboard
- [x] https://github.com/apache/inlong/issues/4979
- [x] https://github.com/apache/inlong/issues/4981
- [x] https://github.com/apache/inlong/issues/4982
- [ ] https://github.com/apache/inlong/issues/4984

### Agent
- [x] https://github.com/apache/inlong/issues/2310
- [x] https://github.com/apache/inlong/issues/4985
- [x] https://github.com/apache/inlong/issues/4986
- [ ] https://github.com/apache/inlong/issues/4987
- [x] https://github.com/apache/inlong/issues/4988

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
