### ISSUE TITLE
[Umbrella] Support  multiple versions of Apache Flink 

### ISSUE THREAD

**Issue by featzhang** [apache/inlong#7260]
### Describe the proposal

The Sort is based on Flink 1.13 currently, but as the continuous increase of business scenarios and the rapid iteration of Flink, the need to adapt to multiple versions to support multiple sort scenarios has become increasingly strong.

### Task list

The modifications involved are:

- [x] #7339
- [x] #7340
- [ ] manager-plugins: used to interact with the flink cluster and submit the connector jar
- [ ] manager: Select different versions or clusters according to different scenarios.

### InLong Component

InLong Manager, InLong Dashboard, InLong Sort

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
it's a big issue, I think we could add related PR to this branch first.
https://github.com/apache/inlong/tree/flink-multi-version

**Comment by GanfengTan** [comment]
#7339

**Comment by dockerzhang** [comment]
duplicated with https://github.com/apache/inlong/issues/8099
