### ISSUE TITLE
[Umbrella] Support  sort management

### ISSUE THREAD

**Issue by featzhang** [apache/inlong#7751]
### Description

<img width="566" alt="image" src="https://user-images.githubusercontent.com/5709212/229132518-c1c7d795-ef3a-4d25-a70a-0fb00e7c2e07.png">

All configurations of Sort currently need to be modified through configuration files on the server side, which is not flexible enough and is highly error-prone. So, could you consider adding a Sort management function to Dashboard?

#### The changes involved are:

- [ ] [Dashboard][Manager] Support `Yarn` cluster in `Cluster Management `
- [ ] [Dashboard][Manager] Support `HDFS` in `Cluster Management `
- [ ] #7754 
- [ ] [Manager] Support `Sort` cluster in `Cluster Management `
- [ ] `Sort Management`:
    - Select computing engines and versions: Flink 1.13.6 as default
    - Different cluster mode: standalone/pre-job/per-session/application
    - Configure the `Yarn` and `HDFS` information (cluster and path) required for Flink to run
    - Configure Flink task concurrency
    - Configure audit info
- [ ] `Sort Monitoring`
    - Yarn resource status
    - Sort job status

#### Motion

<img width="215" alt="image" src="https://user-images.githubusercontent.com/5709212/229185626-56fb9d58-d052-4733-b921-f15f07c3cf8f.png">

<img width="371" alt="image" src="https://user-images.githubusercontent.com/5709212/229266993-ced5ce57-14c4-40cc-b1d2-23537a44dee5.png">

![image](https://user-images.githubusercontent.com/5709212/229341842-2031cbfb-0283-4713-8392-21f929db65df.png)

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aloyszhang** [comment]
This issue has been open for a long time with no activity, close it first and feel free to re-open it if needed.
