### ISSUE TITLE
[Umbrella][Sort] Sort support Flink multi-version

### ISSUE THREAD

**Issue by EMsnap** [apache/inlong#8099]
### Describe the proposal

[Umbrella] Support Flink multi-version packaging and separate sort-formats and cdc-base for multi-version

### Task list

- [x] #8101
- [x] #8062 
- [x] #8065  
- [x] #8220
- [x] #8217
- [x] #8233 
- [x] #8239
- [x] https://github.com/apache/inlong-website/issues/779

### InLong Component

InLong Sort

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
