### ISSUE TITLE
[Umbrella][Manager] Modify the calling method from SDK to HTTP

### ISSUE THREAD

**Issue by dockerzhang** [apache/inlong#8666]
### Describe the proposal

The Manager component uses SDK to execute processes for different services, like Pulsar/Kafka/Elasticsearch...
Using SDK will cause many dependencies, and we could modify the calling method from SDK to HTTP.

### Task list

- [x] https://github.com/apache/inlong/issues/8678
- [x] https://github.com/apache/inlong/issues/8674
- [x] https://github.com/apache/inlong/issues/8676
- [x] https://github.com/apache/inlong/issues/8677

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
