### ISSUE TITLE
[Umbrella] Support Apache Paimon

### ISSUE THREAD

**Issue by featzhang** [apache/inlong#9456]
### Description

[Apache Paimon](https://paimon.apache.org) is an open-source, large-scale language model developed by the Apache Software Foundation. It is designed to provide users with question-answering services, such as answering questions and offering suggestions. Paimon has a rich semantic understanding and computational capabilities, enabling it to handle various types of tasks. It is built using advanced natural language processing techniques and state-of-the-art machine learning algorithms. Paimon is available as a cloud service, allowing users to access its capabilities through APIs and integrate it into their applications.

- [ ] [Feature][Sort] Support Apache Paimon connector 
- [ ] [Feature][Sort] Support load node of Apache Paimon 
- [ ] [Feature][Manager] Support register and manage the resource of Apache Paimon 
- [ ] [Feature][Dashboard] Support Apache Paimon sink management 
- [ ] [Feature][Doc] Add the usage document for Apache Paimon 
- [ ] [Feature][Sort] Support the metric of Apache Paimon 
- [ ] [Feature] [Sort] Support audit of Apache Paimon 
- [ ] [Feature][Sort] Support extract node of Apache Paimon 
- [ ] [Feature][Dashboard] Support Apach Paimon source management
- [ ] [Feature][Manager] Support config Apache Paimon cluster in DataNodeManagement 
- [ ] [Feature][Dashboard] Support Paimon node management

**Comment by aloyszhang** [comment]
This issue has been open for a long time with no activity, close it first and feel free to re-open it if needed.
